name: Push docker image

on:
  push:
    tags:
      - '*'

jobs:
  build-test-push:
    name: Build, test and push image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: slawiko
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.ref }}
            ghcr.io/${{ github.repository }}:latest
#      - name: Build and deploy master image to ghcr.io
#        if: ${{ github.ref == 'refs/heads/master' }}
#        env:
#          GITHUB_PACKAGE_TOKEN: ${{ secrets.PKG_TOKEN }}
#          GITHUB_SHA: ${{ github.sha}}
#          GITHUB_REF: ${{ github.ref}}
#        run: |
#          ref="$(echo ${GITHUB_REF} | cut -d'/' -f3)"
#          echo "GITHUB_REF=${GITHUB_REF}, GITHUB_SHA=${GITHUB_SHA}, GIT_BRANCH=${ref}"
#          echo ${GITHUB_PACKAGE_TOKEN} | docker login ghcr.io -u slawiko --password-stdin
#          docker build --push c-t ghcr.io/slawiko/ru-bel-bot:${ref} .
